name: CI-Generic

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment}}
    steps:
      - uses: actions/checkout@v4
      
      - name: 'Secrets replacement'
        shell: bash
        env:
          WIFI_SSID: ${{ secrets.WIFISSID }}
          WIFI_PWD:  ${{ secrets.WIFIPASSWORD }}
          AP_SSID:   ${{ secrets.APSSID }}
          AP_PWD:    ${{ secrets.APPASSWORD }}
          WEB_USER:  ${{ secrets.WEBUSER }}
          WEB_PWD:   ${{ secrets.WEBPASSWORD }}
          OTA_PWD:   ${{ secrets.OTAPASSWORD }}
        run: |
          sed -i -e 's/\!secret WifiSsid/'"$WIFI_SSID"'/g' scoreboard.yaml
          sed -i -e 's/\!secret WifiPassword/'"$WIFI_PWD"'/g' scoreboard.yaml
          sed -i -e 's/\!secret APSsid/'"$AP_SSID"'/g' scoreboard.yaml
          sed -i -e 's/\!secret APPassword/'"$AP_PWD"'/g' scoreboard.yaml
          sed -i -e 's/\!secret WebUser/'"$WEB_USER"'/g' scoreboard.yaml
          sed -i -e 's/\!secret WebPassword/'"$WEB_PWD"'/g' scoreboard.yaml
          sed -i -e 's/\!secret OTAPassword/'"$OTA_PWD"'/g' scoreboard.yaml

      - uses: esphome/build-action@v6
        with:
          yaml-file: scoreboard.yaml
